### ISSUE TITLE
Active checking the connection and attempting to reconnect

### ISSUE THREAD

**Issue by RCCSilva** [jasonrbriggs/stomp.py#313]
Hello, I have a company project where we use `stomp.py`, but since we started using it I see that sometimes the `on_disconnected` is not called. Since I leave the reconnection logic inside this method, my service stops to work.

I have something like this:

```python
import time
import stomp
from retrying import retry


def stomp_connect(conn, listener_instance):
    conn.set_listener('', listener_instance)
    conn.connect('admin', 'password', wait=True)


class TestListener(stomp.PrintingListener):
    def __init__(self, conn):
        super().__init__(print_to_log=False)
        self._conn = conn

    @retry(wait_exponential_multiplier=1000, wait_exponential_max=10000)
    def _connect_with_retry(self):
        stomp_connect(self._conn, self)

    def on_disconnected(self):
        print('LISTENER DISCONNECTED. Trying to reconnect...')
        self._connect_with_retry()
        print('LISTENER RECONNECTED')


if __name__ == '__main__':
    print('hello')
    stomp_conn = stomp.Connection([('localhost', 61613)])
    test_listener = TestListener(stomp_conn)
    stomp_connect(stomp_conn, test_listener)
    time.sleep(300)
```

and I'm using this Docker to provide the ActiveMQ connection

```yml
version: '3.1'

services:
  activemq:
    image: webcenter/activemq:5.14.3
    environment:
      - ACTIVEMQ_ADMIN_LOGIN=admin
      - ACTIVEMQ_ADMIN_PASSWORD=password
    ports:
      - 61616:61616
      - 61613:61613
```

To get the error I follow this steps:

1. Start the ActiveMQ with `docker-compose up`
2. Start the Python script
3. Stop the ActiveMQ. When I do this, `TestListener` starts the reconnection attempts
4. Restart the ActiveMQ. Once the service is online, `TestListener` gets reconnected.
5. Stop the ActiveMQ a second time. This time `on_disconnected` is not called and the retrying attempt is not started.

Am I doing something wrong?

For now, what I'm doing is to have a separate Thread which checks the connection and if is offline I attempt reconnect. If this this issue is somewhat expected, maybe we could have this feature available in this package.
